export const USER_CREATE = 'ADMINISTRATION/USER_CREATE';
export const USER_DELETE = 'ADMINISTRATION/USERS_DELETE';
export const USER_UPDATE = 'ADMINISTRATION/USER_UPDATE';
export const USERS_INDEX = 'ADMINISTRATION/USERS_INDEX';
