apt_packages:
  - git
  - libpq-dev
  - mc
  - vim
  - wget
  - ruby2.4-dev
  - g++
  - unrar

ruby_version: 2.4

postgresql_version: 9.5

postgresql_databases:
  - name: bitcoin_course_monitoring
    owner: user_bitcoin_course_monitoring
    hstore: yes

# List of database extensions to be created (optional)
postgresql_database_extensions:
  - db: bitcoin_course_monitoring
    extensions:
      - hstore

# List of users to be created (optional)
postgresql_users:
  - name: user_bitcoin_course_monitoring
    pass: 123456
    encrypted: no

# List of user privileges to be applied (optional)
postgresql_user_privileges:
  - name: user_bitcoin_course_monitoring
    db: bitcoin_course_monitoring
    priv: "ALL"
    role_attr_flags: "SUPERUSER"
